### ISSUE TITLE
Cannot run example, any ideas what is going on?

### ISSUE THREAD

**Issue by snaeji** [dlevesque1980/cast#3]
D/FlutterCast( 9656): AppId = ********, application = null
E/MethodChannel#didisoft.cast( 9656): Failed to handle method call
E/MethodChannel#didisoft.cast( 9656): kotlin.KotlinNullPointerException
E/MethodChannel#didisoft.cast( 9656): 	at didisoft.cast.CastOptionsProvider.getCastOptions(CastOptionsProvider.kt:28)
E/MethodChannel#didisoft.cast( 9656): 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
E/MethodChannel#didisoft.cast( 9656): 	at didisoft.cast.CastPlugin.onMethodCall(CastPlugin.kt:48)
E/MethodChannel#didisoft.cast( 9656): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#didisoft.cast( 9656): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#didisoft.cast( 9656): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#didisoft.cast( 9656): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#didisoft.cast( 9656): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#didisoft.cast( 9656): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/MethodChannel#didisoft.cast( 9656): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#didisoft.cast( 9656): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/MethodChannel#didisoft.cast( 9656): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by snaeji** [comment]
And btw this plugin looks really good, excited to try it...

**Comment by dlevesque1980** [comment]
It look like you are not passing a valid AppId. 
You must create an AppId on the chromecast SDK and change the number in the 
example/lib/receiverConst.dart . 

Please tell me if it resolve your problem.
Thank you.

**Comment by snaeji** [comment]
Hi dlevesque1980! I replaced the appid with ***** if you are talking about that, but it was only to not post it publicly. I already have an AppID there.

**Comment by dlevesque1980** [comment]
You app have been publish ? Or your device is set as a debug device?  Because obviously the google sdk is not able to find your Chromecast App.

You can try with this app Id which is the default chromecast app id 
4F8B3483
I found it in this project of google.
https://github.com/googlecast/CastVideos-chrome/blob/master/CastVideos.js

**Comment by wilsharo** [comment]
Hi @dlevesque1980 I am passing the default chromecast app id. The example is still throwing an error at didisoft.cast.CastOptionsProvider.getCastOptions(CastOptionsProvider.kt:28). Can you test on your end by simply cloning your project into a new folder  and running the example to verify that it works?

Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device SM G960F...
D/FlutterCast(14062): AppId = 4F8B3483, application = null
E/MethodChannel#didisoft.cast(14062): Failed to handle method call
E/MethodChannel#didisoft.cast(14062): kotlin.KotlinNullPointerException
E/MethodChannel#didisoft.cast(14062): 	at didisoft.cast.CastOptionsProvider.getCastOptions(CastOptionsProvider.kt:28)
E/MethodChannel#didisoft.cast(14062): 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:5)
E/MethodChannel#didisoft.cast(14062): 	at didisoft.cast.CastPlugin.onMethodCall(CastPlugin.kt:48)
E/MethodChannel#didisoft.cast(14062): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#didisoft.cast(14062): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#didisoft.cast(14062): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#didisoft.cast(14062): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#didisoft.cast(14062): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#didisoft.cast(14062): 	at android.app.ActivityThread.main(ActivityThread.java:6981)
E/MethodChannel#didisoft.cast(14062): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#didisoft.cast(14062): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#didisoft.cast(14062): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
E/flutter (14062): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (14062): PlatformException(error, null, null)
E/flutter (14062): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (14062): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (14062): <asynchronous suspension>
E/flutter (14062): #2      Cast.initChromecast (package:cast/cast.dart:30:34)
E/flutter (14062): <asynchronous suspension>
E/flutter (14062): #3      CastButtonBloc.initialData (package:cast_example/bloc/cast_button_bloc.dart:30:13)
E/flutter (14062): #4      InnerButtonState.build (package:cast_example/widget/cast_button.dart:78:28)
E/flutter (14062): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
E/flutter (14062): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
E/flutter (14062): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (14062): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (14062): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (14062): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (14062): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (14062): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (14062): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (14062): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (14062): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (14062): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (14062): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (14062): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (14062): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (14062): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (14062): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (14062): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (14062): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (14062): #24     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
E/flutter (14062): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (14062): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (14062): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (14062): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (14062): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (14062): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (14062): #31     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
E/flutter (14062): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (14062): #33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
E/flutter (14062): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (14062): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (14062): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (14062): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (14062): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (14062): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (14062): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (14062): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (14062): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (14062): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (14062): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (14062): #45     ComponentElement.mount (package:flutter/src/widgets/fram
D/InputMethodManager(14062): prepareNavigationBarInfo() DecorView@24dd4d3[MainActivity]
D/InputMethodManager(1

**Comment by dlevesque1980** [comment]
You were right. I just push a fix. 
Tell me if you can run it now. For me It work. 

Didier

**Comment by wilsharo** [comment]
It works now. Thanks

**Comment by snaeji** [comment]
Awesome, i haven't had time until now to come back to this. And this works!

**Comment by snaeji** [comment]
@dlevesque1980  or @wilsharo could you confirm that you can actually connect to a Chromecast device after the update? The app runs now without errors but i can't find a Chromecast device. Would be helpful to know if the problem is on my side.

**Comment by dlevesque1980** [comment]
@snaeji : Do you run the app in an emulator or in a real device? 
If you can find the chromecast It might be because the emulator have a simulated network and not actually  your real network. In this case you need a real device to make the test.

**Comment by snaeji** [comment]
@dlevesque1980 thanks for the reply. It was a network issue at work so after your update everything is working as intended. Great job.

**Comment by pharshdev** [comment]
Issue: Cannot find cast device.
Tried: 
1) Using a real android device on a home network.
2) Tested with both registered App Id and the default Id above.
3) Casting to Firestick. Any cast receiver should work right?

I'm able to cast videos from youtube so I don't think there's any network issues. Can you please look into this thanks?

**Comment by dlevesque1980** [comment]
No Amazon FireStick is another protocol entirely not supported. It is call Amazon Fling sdk and must be implemented on both the app on amazon firestick and the app on the mobile. 
see here: https://developer.amazon.com/fling

**Comment by pharshdev** [comment]
> must be implemented on both the app on amazon firestick and the app on the mobile.
Needn’t be implemented on firestick https://developer.amazon.com/docs/fling/working-with-built-in-receiver-on-fire-tv.html . Anyways I need this so I will see if I can implement this as plugin. Thanks.

**Comment by pharshdev** [comment]
> must be implemented on both the app on amazon firestick and the app on the mobile.

Needn’t be implemented on firestick https://developer.amazon.com/docs/fling/working-with-built-in-receiver-on-fire-tv.html . Anyways I need this so I will see if I can implement this as plugin. Thanks.

**Comment by dlevesque1980** [comment]
good to know. Good luck with the plugin

**Comment by pharshdev** [comment]
Firestick/FireTv cast implementation using Fling SDK with player control [https://pub.dev/packages/flutter_fling](url) . This serves my use case but needs more work with support for chromecast.
