### ISSUE TITLE
Support for iOS Casting

### ISSUE THREAD

**Issue by wilsharo** [dlevesque1980/cast#4]
@dlevesque1980 Hi. I see you mentioned you need a paid Apple developer account in order to complete the cast implementation for iOS. I have a paid membership and would gladly add you to my account if you would like. I really need this feature and will start to attempt implementing it this week. However I have no experience with iOS development, only Flutter, so it may take a while for me to get the hang of things. You seem more experienced, so it would be great if you can take this on. Let me know how I can help.

**Comment by dlevesque1980** [comment]
Hi, 
Well I am a dotnet C# experienced developer but not in Kotlin or Swift. All I did for the IOS part was to make sure I can compile de code on the IOS part and the SDK was ready to develop and then I realise I had not what It take to develop it. 

So if you want to share you account with me I would be more than happy to help. But It might take time as the SDK on IOS from my understanding is not the same. I don't if we can fit the present SDK without modifying any Dart code. 

Please contact me on twitter in private @didierlevesque

**Comment by wilsharo** [comment]
Not sure why, but I couldn't message you on Twitter. I sent you a message
on Instagram. Please check there. Thanks

**Comment by robisaks** [comment]
Why was this closed?

**Comment by dlevesque1980** [comment]
We closed it because we had private exchange about that and this should not be public. This is not an issue this is offer for help.

**Comment by robisaks** [comment]
That makes sense. Thanks for putting the Android side out there, it works great!
