### ISSUE TITLE
How to pass meta data?

### ISSUE THREAD

**Issue by adar2378** [dlevesque1980/cast#6]
Can you give me an example of how I could pass metadata for a movie, like subtitle using bundle?

**Comment by dlevesque1980** [comment]
Not sure you can do that. I did not implement nothing for subtitle for now.

Here seems to bebthe documentation of google explaining it

https://developers.google.com/cast/docs/android_sender/media_tracks

**Comment by adar2378** [comment]
Thank you. I'll see if I can manage to send subtitle.
