### ISSUE TITLE
AppID not included for Custom or styled receivers

### ISSUE THREAD

**Issue by snaeji** [dlevesque1980/cast#7]
Hey, i noticed that i couldn't load my custom receiver connected to the appID.

I was able to load the receiver adding this line
`activity.intent.putExtra(CastMediaControlIntent.EXTRA_CAST_APPLICATION_ID, "APPID")`
in CastPlugin.kt line ~300.

**Comment by dlevesque1980** [comment]
Thank you for sharing I will make the correction when I get back from vaccation!

**Comment by dlevesque1980** [comment]
Sorry for the long time it take to answer. But when you check in the example/lib/receiverConts.dart. 
This is where you need to put you app id to make the app work.
